-- ################################################################################
-- #                  Copyright 2014-2022 Novaquark SAS                           #
-- ################################################################################

-----------------------------------------------------------------------------------
-- Raycast
--
-- Raycast represents the restult of a raycast done by a telemeter
-----------------------------------------------------------------------------------
---@class Raycast
---@field hit boolean True if the ray has hit something
---@field distance number Distance to closest object in front
---@field point Vector3 Position of the hit in world coordinates